---
abstract: 'Global Positioning System time'
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
build_requires:
  Math::BigRat: 0.13
  Module::Build: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0
  perl: 5.006
  strict: 0
  warnings: 0
dynamic_config: 0
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Time-GPS
provides:
  Time::GPS:
    file: lib/Time/GPS.pm
    version: 0.003
requires:
  Carp: 0
  Exporter: 0
  Math::BigRat: 0.13
  constant: 0
  parent: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.003
